# =======================
# Builder Stage
# =======================
FROM node:22 AS builder

WORKDIR /usr/src/app

RUN corepack enable && corepack prepare pnpm@10 --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY prisma ./prisma
COPY . .

RUN pnpm prisma generate
RUN pnpm build


# =======================
# Dev Stage
# =======================
FROM node:22 AS dev

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10 --activate

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/package.json ./package.json

ENV NODE_ENV=development

EXPOSE 9000

CMD ["pnpm", "run", "start:dev"]
